
  export const ProjectData = [
    {
      id: 1,
      title: " Personal Portfolio Website with Next.js",
      des: "A clean and modern portfolio website built with Next.js to showcase projects and skills. Fully responsive, featuring smooth animations and easy navigation.",
      img: "/p1.png",
      iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/fm.svg"],
      link: "https://xashadulpo-portfolio.vercel.app",
    },
    {
      id: 2,
      title: "Animated Apple Iphone 3D Website",
      des: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects..",
      img: "/p2.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://iphone-nu.vercel.app",
    },
    {
      id: 3,
      title: "Ethereum Transaction dApp",
      des: " A decentralized application that allows users to connect their MetaMask wallet, send ETH, and view transaction history. Built using Next.js, ethers.js, and Solidity",
      img: "/p3.png",
      iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/c.svg"],
      link: "https://send-eth-test-project.vercel.app",
    },
    {
      id: 4,
      title: "Car Showroom Showcase",
      des: "A sleek website where users can search and explore their favorite cars with advanced filtering options. Featuring a modern UI for a seamless car browsing experience.",
      img: "/p4.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://carhub-neon.vercel.app",
    }, 
    {
      id: 5,
      title: " Amazon Clone",
      des: "A fully responsive e-commerce platform replicating Amazon's features, including product browsing, cart management, and checkout. Built with modern web technologies for a smooth shopping experience.",
      img: "/p5.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://amazon-gamma-rust.vercel.app",
    },
    {
      id: 6,
      title: " Digital Banking App",
      des: "A simple online banking platform where users can add funds, view their account balance, and manage transactions securely. Built for a seamless banking experience.",
      img: "/p5.png",
      iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
      link: "https://bank-liard-eight.vercel.app",
    },
  ];